  const countryList = {
    AED: { code: "AE", name: "United Arab Emirates Dirham" },
    AFN: { code: "AF", name: "Afghan Afghani" },
    XCD: { code: "AG", name: "East Caribbean Dollar" },
    ALL: { code: "AL", name: "Albanian Lek" },
    AMD: { code: "AM", name: "Armenian Dram" },
    ANG: { code: "AN", name: "Netherlands Antillean Guilder" },
    AOA: { code: "AO", name: "Angolan Kwanza" },
    AQD: { code: "AQ", name: "Antarctic Dollar" },
    ARS: { code: "AR", name: "Argentine Peso" },
    AUD: { code: "AU", name: "Australian Dollar" },
    AZN: { code: "AZ", name: "Azerbaijani Manat" },
    BAM: { code: "BA", name: "Bosnia and Herzegovina Convertible Mark" },
    BBD: { code: "BB", name: "Barbadian Dollar" },
    BDT: { code: "BD", name: "Bangladeshi Taka" },
    XOF: { code: "BE", name: "West African CFA Franc" },
    BGN: { code: "BG", name: "Bulgarian Lev" },
    BHD: { code: "BH", name: "Bahraini Dinar" },
    BIF: { code: "BI", name: "Burundian Franc" },
    BMD: { code: "BM", name: "Bermudian Dollar" },
    BND: { code: "BN", name: "Brunei Dollar" },
    BOB: { code: "BO", name: "Bolivian Boliviano" },
    BRL: { code: "BR", name: "Brazilian Real" },
    BSD: { code: "BS", name: "Bahamian Dollar" },
    NOK: { code: "BV", name: "Norwegian Krone" },
    BWP: { code: "BW", name: "Botswana Pula" },
    BYR: { code: "BY", name: "Belarusian Ruble" },
    BZD: { code: "BZ", name: "Belize Dollar" },
    CAD: { code: "CA", name: "Canadian Dollar" },
    CDF: { code: "CD", name: "Congolese Franc" },
    XAF: { code: "CF", name: "Central African CFA Franc" },
    CHF: { code: "CH", name: "Swiss Franc" },
    CLP: { code: "CL", name: "Chilean Peso" },
    CNY: { code: "CN", name: "Chinese Yuan" },
    COP: { code: "CO", name: "Colombian Peso" },
    CRC: { code: "CR", name: "Costa Rican Colón" },
    CUP: { code: "CU", name: "Cuban Peso" },
    CVE: { code: "CV", name: "Cape Verdean Escudo" },
    CYP: { code: "CY", name: "Cypriot Pound" },
    CZK: { code: "CZ", name: "Czech Koruna" },
    DJF: { code: "DJ", name: "Djiboutian Franc" },
    DKK: { code: "DK", name: "Danish Krone" },
    DOP: { code: "DO", name: "Dominican Peso" },
    DZD: { code: "DZ", name: "Algerian Dinar" },
    ECS: { code: "EC", name: "Ecuadorian Sucre" },
    EEK: { code: "EE", name: "Estonian Kroon" },
    EGP: { code: "EG", name: "Egyptian Pound" },
    ETB: { code: "ET", name: "Ethiopian Birr" },
    EUR: { code: "FR", name: "Euro" },
    FJD: { code: "FJ", name: "Fijian Dollar" },
    FKP: { code: "FK", name: "Falkland Islands Pound" },
    GBP: { code: "GB", name: "British Pound" },
    GEL: { code: "GE", name: "Georgian Lari" },
    GGP: { code: "GG", name: "Guernsey Pound" },
    GHS: { code: "GH", name: "Ghanaian Cedi" },
    GIP: { code: "GI", name: "Gibraltar Pound" },
    GMD: { code: "GM", name: "Gambian Dalasi" },
    GNF: { code: "GN", name: "Guinean Franc" },
    GTQ: { code: "GT", name: "Guatemalan Quetzal" },
    GYD: { code: "GY", name: "Guyanese Dollar" },
    HKD: { code: "HK", name: "Hong Kong Dollar" },
    HNL: { code: "HN", name: "Honduran Lempira" },
    HRK: { code: "HR", name: "Croatian Kuna" },
    HTG: { code: "HT", name: "Haitian Gourde" },
    HUF: { code: "HU", name: "Hungarian Forint" },
    IDR: { code: "ID", name: "Indonesian Rupiah" },
    ILS: { code: "IL", name: "Israeli New Shekel" },
    INR: { code: "IN", name: "Indian Rupee" },
    IQD: { code: "IQ", name: "Iraqi Dinar" },
    IRR: { code: "IR", name: "Iranian Rial" },
    ISK: { code: "IS", name: "Icelandic Króna" },
    JMD: { code: "JM", name: "Jamaican Dollar" },
    JOD: { code: "JO", name: "Jordanian Dinar" },
    JPY: { code: "JP", name: "Japanese Yen" },
    KES: { code: "KE", name: "Kenyan Shilling" },
    KGS: { code: "KG", name: "Kyrgyzstani Som" },
    KHR: { code: "KH", name: "Cambodian Riel" },
    KMF: { code: "KM", name: "Comorian Franc" },
    KPW: { code: "KP", name: "North Korean Won" },
    KRW: { code: "KR", name: "South Korean Won" },
    KWD: { code: "KW", name: "Kuwaiti Dinar" },
    KYD: { code: "KY", name: "Cayman Islands Dollar" },
    KZT: { code: "KZ", name: "Kazakhstani Tenge" },
    LAK: { code: "LA", name: "Lao Kip" },
    LBP: { code: "LB", name: "Lebanese Pound" },
    LKR: { code: "LK", name: "Sri Lankan Rupee" },
    LRD: { code: "LR", name: "Liberian Dollar" },
    LSL: { code: "LS", name: "Lesotho Loti" },
    LTL: { code: "LT", name: "Lithuanian Litas" },
    LVL: { code: "LV", name: "Latvian Lats" },
    LYD: { code: "LY", name: "Libyan Dinar" },
    MAD: { code: "MA", name: "Moroccan Dirham" },
    MDL: { code: "MD", name: "Moldovan Leu" },
    MGA: { code: "MG", name: "Malagasy Ariary" },
    MKD: { code: "MK", name: "Macedonian Denar" },
    MMK: { code: "MM", name: "Myanmar Kyat" },
    MNT: { code: "MN", name: "Mongolian Tugrik" },
    MOP: { code: "MO", name: "Macanese Pataca" },
    MRO: { code: "MR", name: "Mauritanian Ouguiya" },
    MTL: { code: "MT", name: "Maltese Lira" },
    MUR: { code: "MU", name: "Mauritian Rupee" },
    MVR: { code: "MV", name: "Maldivian Rufiyaa" },
    MWK: { code: "MW", name: "Malawian Kwacha" },
    MXN: { code: "MX", name: "Mexican Peso" },
    MYR: { code: "MY", name: "Malaysian Ringgit" },
    MZN: { code: "MZ", name: "Mozambican Metical" },
    NAD: { code: "NA", name: "Namibian Dollar" },
    XPF: { code: "NC", name: "CFP Franc" },
    NGN: { code: "NG", name: "Nigerian Naira" },
    NIO: { code: "NI", name: "Nicaraguan Córdoba" },
    NPR: { code: "NP", name: "Nepalese Rupee" },
    NZD: { code: "NZ", name: "New Zealand Dollar" },
    OMR: { code: "OM", name: "Omani Rial" },
    PAB: { code: "PA", name: "Panamanian Balboa" },
    PEN: { code: "PE", name: "Peruvian Nuevo Sol" },
    PGK: { code: "PG", name: "Papua New Guinean Kina" },
    PHP: { code: "PH", name: "Philippine Peso" },
    PKR: { code: "PK", name: "Pakistani Rupee" },
    PLN: { code: "PL", name: "Polish Zloty" },
    PYG: { code: "PY", name: "Paraguayan Guarani" },
    QAR: { code: "QA", name: "Qatari Rial" },
    RON: { code: "RO", name: "Romanian Leu" },
    RSD: { code: "RS", name: "Serbian Dinar" },
    RUB: { code: "RU", name: "Russian Ruble" },
    RWF: { code: "RW", name: "Rwandan Franc" },
    SAR: { code: "SA", name: "Saudi Riyal" },
    SBD: { code: "SB", name: "Solomon Islands Dollar" },
    SCR: { code: "SC", name: "Seychellois Rupee" },
    SDG: { code: "SD", name: "Sudanese Pound" },
    SEK: { code: "SE", name: "Swedish Krona" },
    SGD: { code: "SG", name: "Singapore Dollar" },
    SKK: { code: "SK", name: "Slovak Koruna" },
    SLL: { code: "SL", name: "Sierra Leonean Leone" },
    SOS: { code: "SO", name: "Somali Shilling" },
    SRD: { code: "SR", name: "Surinamese Dollar" },
    STD: { code: "ST", name: "São Tomé and Príncipe Dobra" },
    SVC: { code: "SV", name: "Salvadoran Colón" },
    SYP: { code: "SY", name: "Syrian Pound" },
    SZL: { code: "SZ", name: "Swazi Lilangeni" },
    THB: { code: "TH", name: "Thai Baht" },
    TJS: { code: "TJ", name: "Tajikistani Somoni" },
    TMT: { code: "TM", name: "Turkmenistan Manat" },
    TND: { code: "TN", name: "Tunisian Dinar" },
    TOP: { code: "TO", name: "Tongan Paʻanga" },
    TRY: { code: "TR", name: "Turkish Lira" },
    TTD: { code: "TT", name: "Trinidad and Tobago Dollar" },
    TWD: { code: "TW", name: "New Taiwan Dollar" },
    TZS: { code: "TZ", name: "Tanzanian Shilling" },
    UAH: { code: "UA", name: "Ukrainian Hryvnia" },
    UGX: { code: "UG", name: "Ugandan Shilling" },
    USD: { code: "US", name: "United States Dollar" },
    UYU: { code: "UY", name: "Uruguayan Peso" },
    UZS: { code: "UZ", name: "Uzbekistani Som" },
    VEF: { code: "VE", name: "Venezuelan Bolívar" },
    VND: { code: "VN", name: "Vietnamese Đồng" },
    VUV: { code: "VU", name: "Vanuatu Vatu" },
    YER: { code: "YE", name: "Yemeni Rial" },
    ZAR: { code: "ZA", name: "South African Rand" },
    ZMK: { code: "ZM", name: "Zambian Kwacha" },
    ZWD: { code: "ZW", name: "Zimbabwean Dollar" },
};
